In [1]:
##Niddle Man final version 
#import numpy
import numpy as np
#read sequence 
seq1="ATCGT"
seq2="TGGTG"

#seq2="CTCGCAGC"
#seq1="CATTCAC"

# Scoring schema
match=1
misMatch=-1
gap=-2

#find the length 
lenSeq1=len(seq1)
lenSeq2=len(seq2)

# allignment matrix
allignmentMatrix=np.full((len(seq1)+1,len(seq2)+1),-999)
for i in range(lenSeq1+1):
    allignmentMatrix[i,0]=i*gap 
for j in range(lenSeq2+1):
    allignmentMatrix[0,j]=j*gap 
    

print('Sequence1 is ',seq1,' with lenght ',lenSeq1)
print('Sequence2 is ',seq2,' with lenght ',lenSeq2)
print('Scoring Schema')
print('Match:',match)
print('MisMatch:',misMatch)
print('gap:',gap)
print(allignmentMatrix)

#Create a dictionary for sequence 
seq1Dic={}
seq1Dic[0]='GAP'
seq2Dic={}
seq2Dic[0]='GAP'
for i in range(1,lenSeq1+1):
    seq1Dic[i]=seq1[i-1]
for j in range(1,lenSeq2+1):
    seq2Dic[j]=seq2[j-1]
    
print(seq1Dic,seq2Dic)
#function for scoring matrix 
def findScore(nuc1,nuc2):
    if nuc1 not in seq1Dic.keys():
        return misMatch
    if nuc2 not in seq2Dic.keys():
        return misMatch
    if seq1Dic[nuc1] == seq2Dic[nuc2]:
        return match
    else:
        return misMatch 

#fill the allignment matrix 
for i in range(1,lenSeq1+1):
    for j in range(1,lenSeq2+1):       
        allignmentMatrix[i,j]=max(allignmentMatrix[i-1,j-1]+findScore(i,j),allignmentMatrix[i,j-1]+gap,allignmentMatrix[i-1,j]+gap)
print("allignment matrix after filling ")
print(allignmentMatrix)

#Back Tracing and allignment 
allSeq1=''
allSeq2=''
i=lenSeq1
j=lenSeq2

while i!=0 and j!=0:
    if findScore(i,j)==match:
        allSeq1=allSeq1+seq1Dic[i]
        allSeq2=allSeq2+seq2Dic[j]
        i=i-1
        j=j-1
    else:
        left=allignmentMatrix[i,j-1]
        up=allignmentMatrix[i-1,j]
        diagonal=allignmentMatrix[i-1,j-1]
        if diagonal  > left and  diagonal > up: 
            allSeq1=allSeq1+seq1Dic[i]
            allSeq2=allSeq2+seq2Dic[j]
            i=i-1
            j=j-1
        elif left >=diagonal and left >=up:
            allSeq1=allSeq1+'-'
            allSeq2=allSeq2+seq2Dic[j]
            j=j-1
        else:
            allSeq1=allSeq1+seq1Dic[i]
            allSeq2=allSeq2+'-'
            i=i-1
while seq1Dic[i]!='GAP':
    allSeq1=allSeq1+seq1Dic[i]
    i=i-1
    allSeq2=allSeq2+'-'
while seq2Dic[j]!='GAP':
    allSeq2=allSeq2+seq2Dic[j]
    j=j-1
    allSeq1=allSeq1+'-'

    
             
print("allignment of Sequences")
print(allSeq1[::-1])
print(allSeq2[::-1])

Sequence1 is  ATCGT  with lenght  5
Sequence2 is  TGGTG  with lenght  5
Scoring Schema
Match: 1
MisMatch: -1
gap: -2
[[   0   -2   -4   -6   -8  -10]
 [  -2 -999 -999 -999 -999 -999]
 [  -4 -999 -999 -999 -999 -999]
 [  -6 -999 -999 -999 -999 -999]
 [  -8 -999 -999 -999 -999 -999]
 [ -10 -999 -999 -999 -999 -999]]
{0: 'GAP', 1: 'A', 2: 'T', 3: 'C', 4: 'G', 5: 'T'} {0: 'GAP', 1: 'T', 2: 'G', 3: 'G', 4: 'T', 5: 'G'}
allignment matrix after filling 
[[  0  -2  -4  -6  -8 -10]
 [ -2  -1  -3  -5  -7  -9]
 [ -4  -1  -2  -4  -4  -6]
 [ -6  -3  -2  -3  -5  -5]
 [ -8  -5  -2  -1  -3  -4]
 [-10  -7  -4  -3   0  -2]]
allignment of Sequences
ATCGT-
-TGGTG
