In [1]:
#Smith-Waterman algorithm final version
#import numpy
import numpy as np
#read sequence 
seq1="ACCTAAGG"
seq2="GGCTCAATCA"

#seq1="TGTTACGG"
#seq2="GGTTGACTA"

# Scoring schema
match=2
misMatch=-1
gap=-2

#find the length 
lenSeq1=len(seq1)
lenSeq2=len(seq2)

# allignment matrix
allignmentMatrix=np.zeros((len(seq1)+1,len(seq2)+1))

print('Sequence1 is ',seq1,' with lenght ',lenSeq1)
print('Sequence2 is ',seq2,' with lenght ',lenSeq2)
print('Scoring Schema')
print('Match:',match)
print('MisMatch:',misMatch)
print('gap:',gap)
print(allignmentMatrix)

#Create a dictionary for sequence 
seq1Dic={}
seq1Dic[0]='GAP'
seq2Dic={}
seq2Dic[0]='GAP'
for i in range(1,lenSeq1+1):
    seq1Dic[i]=seq1[i-1]
for j in range(1,lenSeq2+1):
    seq2Dic[j]=seq2[j-1]

#function for scoring matrix 
def findScore(nuc1,nuc2):
    if nuc1 not in seq1Dic.keys():
        return misMatch
    if nuc2 not in seq2Dic.keys():
        return misMatch
    if seq1Dic[nuc1] == seq2Dic[nuc2]:
        return match
    else:
        return misMatch

#fill the allignment matrix 
for i in range(1,lenSeq1+1):
    for j in range(1,lenSeq2+1):
        maxValue=max(allignmentMatrix[i-1,j-1]+findScore(i,j),allignmentMatrix[i,j-1]+gap,allignmentMatrix[i-1,j]+gap)
       # print(i,j,seq1Dic[i],seq2Dic[j],findScore(i,j),maxValue)
        if maxValue > 0:
            allignmentMatrix[i,j]=maxValue
        else:
            allignmentMatrix[i,j]=0   
            
print("allignment matrix after filling ")
print(allignmentMatrix)

#Back Tracing and allignment 
allSeq1=''
allSeq2=''
# Find the index of the maximum element
max_index = np.argmax(allignmentMatrix)

# Convert the 1D index to 2D indices (row, column)
num_rows, num_cols = allignmentMatrix.shape
max_row, max_col = divmod(max_index, num_cols)
maxValue=allignmentMatrix[6,7]
i=max_row
j=max_col

while allignmentMatrix[i,j]!=0:
    if findScore(i,j)==match:
        allSeq1=allSeq1+seq1Dic[i]
        allSeq2=allSeq2+seq2Dic[j]
        i=i-1
        j=j-1
    else:
        left=allignmentMatrix[i,j-1]
        up=allignmentMatrix[i-1,j]
        diagonal=allignmentMatrix[i-1,j-1]
        if diagonal  > left and  diagonal > up: 
            allSeq1=allSeq1+seq1Dic[i]
            allSeq2=allSeq2+seq2Dic[j]
            i=i-1
            j=j-1
        elif left >=diagonal and left >=up:
            allSeq1=allSeq1+'-'
            allSeq2=allSeq2+seq2Dic[j]
            j=j-1
        else:
            allSeq1=allSeq1+seq1Dic[i]
            allSeq2=allSeq2+'-'
            i=i-1
print("allignment of Sequences")
print(allSeq1[::-1])
print(allSeq2[::-1])

Sequence1 is  ACCTAAGG  with lenght  8
Sequence2 is  GGCTCAATCA  with lenght  10
Scoring Schema
Match: 2
MisMatch: -1
gap: -2
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
allignment matrix after filling 
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 2. 2. 0. 0. 2.]
 [0. 0. 0. 2. 0. 2. 0. 1. 1. 2. 0.]
 [0. 0. 0. 2. 1. 2. 1. 0. 0. 3. 1.]
 [0. 0. 0. 0. 4. 2. 1. 0. 2. 1. 2.]
 [0. 0. 0. 0. 2. 3. 4. 3. 1. 1. 3.]
 [0. 0. 0. 0. 0. 1. 5. 6. 4. 2. 3.]
 [0. 2. 2. 0. 0. 0. 3. 4. 5. 3. 1.]
 [0. 2. 4. 2. 0. 0. 1. 2. 3. 4. 2.]]
allignment of Sequences
CT-AA
CTCAA
